"""agent core

Revision ID: ac18980a9b69
Revises: 20260820_0001
Create Date: 2026-08-21 06:17:36.762266
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ac18980a9b69'
down_revision: Union[str, None] = '20260820_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for value in (
        'retry_wait',
        'paused',
        'canceling',
        'canceled',
        'manual_intervention',
    ):
        op.execute(f"ALTER TYPE workflowstatus ADD VALUE IF NOT EXISTS '{value}'")
    op.create_table('tenants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_index(op.f('ix_tenants_status'), 'tenants', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('external_subject', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_external_subject'), 'users', ['external_subject'], unique=True)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_table('ip_profile_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('ip_profile_id', sa.String(length=36), nullable=True),
    sa.Column('profile_version', sa.Integer(), nullable=False),
    sa.Column('snapshot_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ip_profile_id'], ['ip_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'ip_profile_id', 'profile_version', name='uq_ip_snapshot_version')
    )
    op.create_index(op.f('ix_ip_profile_snapshots_ip_profile_id'), 'ip_profile_snapshots', ['ip_profile_id'], unique=False)
    op.create_index(op.f('ix_ip_profile_snapshots_tenant_id'), 'ip_profile_snapshots', ['tenant_id'], unique=False)
    op.create_table('memberships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'user_id', name='uq_membership_tenant_user')
    )
    op.create_index(op.f('ix_memberships_status'), 'memberships', ['status'], unique=False)
    op.create_index(op.f('ix_memberships_tenant_id'), 'memberships', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_table('outbox_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('aggregate_type', sa.String(length=64), nullable=False),
    sa.Column('aggregate_id', sa.String(length=36), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=200), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key')
    )
    op.create_index(op.f('ix_outbox_events_aggregate_id'), 'outbox_events', ['aggregate_id'], unique=False)
    op.create_index(op.f('ix_outbox_events_available_at'), 'outbox_events', ['available_at'], unique=False)
    op.create_index(op.f('ix_outbox_events_published_at'), 'outbox_events', ['published_at'], unique=False)
    op.create_index(op.f('ix_outbox_events_tenant_id'), 'outbox_events', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_outbox_events_topic'), 'outbox_events', ['topic'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('settings_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_created_by_user_id'), 'projects', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_index(op.f('ix_projects_tenant_id'), 'projects', ['tenant_id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('media_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('provider_path', sa.String(length=500), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('metadata_payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_assets_created_by_user_id'), 'assets', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_assets_project_id'), 'assets', ['project_id'], unique=False)
    op.create_index(op.f('ix_assets_status'), 'assets', ['status'], unique=False)
    op.create_index(op.f('ix_assets_tenant_id'), 'assets', ['tenant_id'], unique=False)
    op.create_table('content_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_items_project_id'), 'content_items', ['project_id'], unique=False)
    op.create_index(op.f('ix_content_items_status'), 'content_items', ['status'], unique=False)
    op.create_index(op.f('ix_content_items_tenant_id'), 'content_items', ['tenant_id'], unique=False)
    op.create_table('consent_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('consent_type', sa.String(length=64), nullable=False),
    sa.Column('grantor', sa.String(length=200), nullable=False),
    sa.Column('scope_text', sa.Text(), nullable=False),
    sa.Column('evidence_payload', sa.JSON(), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consent_snapshots_asset_id'), 'consent_snapshots', ['asset_id'], unique=False)
    op.create_index(op.f('ix_consent_snapshots_tenant_id'), 'consent_snapshots', ['tenant_id'], unique=False)
    op.create_table('production_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('content_item_id', sa.String(length=36), nullable=True),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('ip_profile_snapshot_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('intent_text', sa.Text(), nullable=False),
    sa.Column('intent_spec', sa.JSON(), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('automation_mode', sa.String(length=32), nullable=False),
    sa.Column('checkpoint_policy', sa.JSON(), nullable=False),
    sa.Column('external_side_effect_policy', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'planning', 'awaiting_plan_approval', 'queued', 'running', 'awaiting_decision', 'evaluating', 'retry_wait', 'paused', 'canceling', 'canceled', 'succeeded', 'failed_retryable', 'failed_final', 'manual_intervention', name='productionorderstatus'), nullable=False),
    sa.Column('budget_limit', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('max_auto_rework', sa.Integer(), nullable=False),
    sa.Column('auto_rework_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ip_profile_snapshot_id'], ['ip_profile_snapshots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name='uq_order_tenant_idempotency')
    )
    op.create_index(op.f('ix_production_orders_content_item_id'), 'production_orders', ['content_item_id'], unique=False)
    op.create_index(op.f('ix_production_orders_created_by_user_id'), 'production_orders', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_production_orders_project_id'), 'production_orders', ['project_id'], unique=False)
    op.create_index(op.f('ix_production_orders_status'), 'production_orders', ['status'], unique=False)
    op.create_index(op.f('ix_production_orders_tenant_id'), 'production_orders', ['tenant_id'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('production_order_id', sa.String(length=36), nullable=False),
    sa.Column('run_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('planning', 'running', 'awaiting_decision', 'evaluating', 'succeeded', 'failed', 'canceled', name='agentrunstatus'), nullable=False),
    sa.Column('context_snapshot', sa.JSON(), nullable=False),
    sa.Column('stop_reason', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('production_order_id', 'run_number', name='uq_agent_run_number')
    )
    op.create_index(op.f('ix_agent_runs_production_order_id'), 'agent_runs', ['production_order_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_status'), 'agent_runs', ['status'], unique=False)
    op.create_index(op.f('ix_agent_runs_tenant_id'), 'agent_runs', ['tenant_id'], unique=False)
    op.create_table('artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('production_order_id', sa.String(length=36), nullable=False),
    sa.Column('content_item_id', sa.String(length=36), nullable=True),
    sa.Column('artifact_key', sa.String(length=100), nullable=False),
    sa.Column('artifact_type', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('production_order_id', 'artifact_key', name='uq_order_artifact_key')
    )
    op.create_index(op.f('ix_artifacts_artifact_type'), 'artifacts', ['artifact_type'], unique=False)
    op.create_index(op.f('ix_artifacts_content_item_id'), 'artifacts', ['content_item_id'], unique=False)
    op.create_index(op.f('ix_artifacts_production_order_id'), 'artifacts', ['production_order_id'], unique=False)
    op.create_index(op.f('ix_artifacts_tenant_id'), 'artifacts', ['tenant_id'], unique=False)
    op.create_table('asset_refs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('production_order_id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('production_order_id', 'asset_id', 'role', name='uq_order_asset_role')
    )
    op.create_index(op.f('ix_asset_refs_asset_id'), 'asset_refs', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_refs_production_order_id'), 'asset_refs', ['production_order_id'], unique=False)
    op.create_index(op.f('ix_asset_refs_tenant_id'), 'asset_refs', ['tenant_id'], unique=False)
    op.create_table('agent_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('production_order_id', sa.String(length=36), nullable=False),
    sa.Column('agent_run_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_events_agent_run_id'), 'agent_events', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_agent_events_created_at'), 'agent_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_events_event_type'), 'agent_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_agent_events_production_order_id'), 'agent_events', ['production_order_id'], unique=False)
    op.create_index(op.f('ix_agent_events_tenant_id'), 'agent_events', ['tenant_id'], unique=False)
    op.create_table('plan_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('agent_run_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('success_criteria', sa.JSON(), nullable=False),
    sa.Column('plan_payload', sa.JSON(), nullable=False),
    sa.Column('budget_estimate', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'superseded', 'completed', name='planversionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_run_id', 'version', name='uq_plan_run_version')
    )
    op.create_index(op.f('ix_plan_versions_agent_run_id'), 'plan_versions', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_plan_versions_status'), 'plan_versions', ['status'], unique=False)
    op.create_index(op.f('ix_plan_versions_tenant_id'), 'plan_versions', ['tenant_id'], unique=False)
    op.create_table('artifact_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('artifact_id', sa.String(length=36), nullable=False),
    sa.Column('plan_version_id', sa.String(length=36), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('candidate', 'approved', 'returned', 'superseded', name='artifactversionstatus'), nullable=False),
    sa.Column('content_payload', sa.JSON(), nullable=False),
    sa.Column('lineage_payload', sa.JSON(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_version_id'], ['plan_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artifact_id', 'version', name='uq_artifact_version')
    )
    op.create_index(op.f('ix_artifact_versions_artifact_id'), 'artifact_versions', ['artifact_id'], unique=False)
    op.create_index(op.f('ix_artifact_versions_plan_version_id'), 'artifact_versions', ['plan_version_id'], unique=False)
    op.create_index(op.f('ix_artifact_versions_status'), 'artifact_versions', ['status'], unique=False)
    op.create_index(op.f('ix_artifact_versions_tenant_id'), 'artifact_versions', ['tenant_id'], unique=False)
    op.create_table('decision_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('production_order_id', sa.String(length=36), nullable=False),
    sa.Column('agent_run_id', sa.String(length=36), nullable=False),
    sa.Column('plan_version_id', sa.String(length=36), nullable=True),
    sa.Column('reason_code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('recommended_option', sa.String(length=64), nullable=True),
    sa.Column('blocking', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'resolved', 'canceled', name='decisionstatus'), nullable=False),
    sa.Column('resolved_option', sa.String(length=64), nullable=True),
    sa.Column('resolution_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_version_id'], ['plan_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_requests_agent_run_id'), 'decision_requests', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_decision_requests_plan_version_id'), 'decision_requests', ['plan_version_id'], unique=False)
    op.create_index(op.f('ix_decision_requests_production_order_id'), 'decision_requests', ['production_order_id'], unique=False)
    op.create_index(op.f('ix_decision_requests_reason_code'), 'decision_requests', ['reason_code'], unique=False)
    op.create_index(op.f('ix_decision_requests_status'), 'decision_requests', ['status'], unique=False)
    op.create_index(op.f('ix_decision_requests_tenant_id'), 'decision_requests', ['tenant_id'], unique=False)
    op.create_table('quality_evaluations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('artifact_version_id', sa.String(length=36), nullable=False),
    sa.Column('evaluator_key', sa.String(length=100), nullable=False),
    sa.Column('evaluator_version', sa.String(length=64), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('score_payload', sa.JSON(), nullable=False),
    sa.Column('issue_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artifact_version_id'], ['artifact_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_evaluations_artifact_version_id'), 'quality_evaluations', ['artifact_version_id'], unique=False)
    op.create_index(op.f('ix_quality_evaluations_tenant_id'), 'quality_evaluations', ['tenant_id'], unique=False)
    op.create_table('step_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('workflow_step_id', sa.String(length=36), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('input_payload', sa.JSON(), nullable=False),
    sa.Column('output_payload', sa.JSON(), nullable=True),
    sa.Column('error_code', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_step_id'], ['workflow_steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_step_id', 'attempt_number', name='uq_step_attempt_number')
    )
    op.create_index(op.f('ix_step_attempts_status'), 'step_attempts', ['status'], unique=False)
    op.create_index(op.f('ix_step_attempts_tenant_id'), 'step_attempts', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_step_attempts_workflow_id'), 'step_attempts', ['workflow_id'], unique=False)
    op.create_index(op.f('ix_step_attempts_workflow_step_id'), 'step_attempts', ['workflow_step_id'], unique=False)
    op.add_column('provider_jobs', sa.Column('tenant_id', sa.String(length=36), nullable=True))
    op.add_column('provider_jobs', sa.Column('step_attempt_id', sa.String(length=36), nullable=True))
    op.add_column('provider_jobs', sa.Column('capability', sa.String(length=100), server_default='avatar.render', nullable=False))
    op.add_column('provider_jobs', sa.Column('connection_id', sa.String(length=36), nullable=True))
    op.add_column('provider_jobs', sa.Column('idempotency_key', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_provider_jobs_capability'), 'provider_jobs', ['capability'], unique=False)
    op.create_index(op.f('ix_provider_jobs_connection_id'), 'provider_jobs', ['connection_id'], unique=False)
    op.create_index(op.f('ix_provider_jobs_idempotency_key'), 'provider_jobs', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_provider_jobs_step_attempt_id'), 'provider_jobs', ['step_attempt_id'], unique=False)
    op.create_index(op.f('ix_provider_jobs_tenant_id'), 'provider_jobs', ['tenant_id'], unique=False)
    op.create_foreign_key('provider_jobs_tenant_id_fkey', 'provider_jobs', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('provider_jobs_step_attempt_id_fkey', 'provider_jobs', 'step_attempts', ['step_attempt_id'], ['id'], ondelete='SET NULL')
    op.add_column('workflow_route_decisions', sa.Column('tenant_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_workflow_route_decisions_tenant_id'), 'workflow_route_decisions', ['tenant_id'], unique=False)
    op.create_foreign_key('workflow_route_decisions_tenant_id_fkey', 'workflow_route_decisions', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('workflow_runs', sa.Column('tenant_id', sa.String(length=36), nullable=True))
    op.add_column('workflow_runs', sa.Column('production_order_id', sa.String(length=36), nullable=True))
    op.add_column('workflow_runs', sa.Column('plan_version_id', sa.String(length=36), nullable=True))
    op.add_column('workflow_runs', sa.Column('capability', sa.String(length=100), server_default='avatar.render', nullable=False))
    op.add_column('workflow_runs', sa.Column('lease_owner', sa.String(length=128), nullable=True))
    op.add_column('workflow_runs', sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('workflow_runs', sa.Column('next_wakeup_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_workflow_runs_capability'), 'workflow_runs', ['capability'], unique=False)
    op.create_index(op.f('ix_workflow_runs_lease_expires_at'), 'workflow_runs', ['lease_expires_at'], unique=False)
    op.create_index(op.f('ix_workflow_runs_lease_owner'), 'workflow_runs', ['lease_owner'], unique=False)
    op.create_index(op.f('ix_workflow_runs_next_wakeup_at'), 'workflow_runs', ['next_wakeup_at'], unique=False)
    op.create_index(op.f('ix_workflow_runs_plan_version_id'), 'workflow_runs', ['plan_version_id'], unique=False)
    op.create_index(op.f('ix_workflow_runs_production_order_id'), 'workflow_runs', ['production_order_id'], unique=False)
    op.create_index(op.f('ix_workflow_runs_tenant_id'), 'workflow_runs', ['tenant_id'], unique=False)
    op.create_foreign_key('workflow_runs_tenant_id_fkey', 'workflow_runs', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('workflow_runs_production_order_id_fkey', 'workflow_runs', 'production_orders', ['production_order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('workflow_runs_plan_version_id_fkey', 'workflow_runs', 'plan_versions', ['plan_version_id'], ['id'], ondelete='SET NULL')
    op.add_column('workflow_steps', sa.Column('capability', sa.String(length=100), nullable=True))
    op.add_column('workflow_steps', sa.Column('depends_on', sa.JSON(), server_default=sa.text("'[]'::json"), nullable=False))
    op.add_column('workflow_steps', sa.Column('expected_artifact', sa.String(length=100), nullable=True))
    op.add_column('workflow_steps', sa.Column('checkpoint', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_steps', 'checkpoint')
    op.drop_column('workflow_steps', 'expected_artifact')
    op.drop_column('workflow_steps', 'depends_on')
    op.drop_column('workflow_steps', 'capability')
    op.drop_constraint('workflow_runs_plan_version_id_fkey', 'workflow_runs', type_='foreignkey')
    op.drop_constraint('workflow_runs_production_order_id_fkey', 'workflow_runs', type_='foreignkey')
    op.drop_constraint('workflow_runs_tenant_id_fkey', 'workflow_runs', type_='foreignkey')
    op.drop_index(op.f('ix_workflow_runs_tenant_id'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_production_order_id'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_plan_version_id'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_next_wakeup_at'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_lease_owner'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_lease_expires_at'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_capability'), table_name='workflow_runs')
    op.drop_column('workflow_runs', 'next_wakeup_at')
    op.drop_column('workflow_runs', 'lease_expires_at')
    op.drop_column('workflow_runs', 'lease_owner')
    op.drop_column('workflow_runs', 'capability')
    op.drop_column('workflow_runs', 'plan_version_id')
    op.drop_column('workflow_runs', 'production_order_id')
    op.drop_column('workflow_runs', 'tenant_id')
    op.drop_constraint('workflow_route_decisions_tenant_id_fkey', 'workflow_route_decisions', type_='foreignkey')
    op.drop_index(op.f('ix_workflow_route_decisions_tenant_id'), table_name='workflow_route_decisions')
    op.drop_column('workflow_route_decisions', 'tenant_id')
    op.drop_constraint('provider_jobs_step_attempt_id_fkey', 'provider_jobs', type_='foreignkey')
    op.drop_constraint('provider_jobs_tenant_id_fkey', 'provider_jobs', type_='foreignkey')
    op.drop_index(op.f('ix_provider_jobs_tenant_id'), table_name='provider_jobs')
    op.drop_index(op.f('ix_provider_jobs_step_attempt_id'), table_name='provider_jobs')
    op.drop_index(op.f('ix_provider_jobs_idempotency_key'), table_name='provider_jobs')
    op.drop_index(op.f('ix_provider_jobs_connection_id'), table_name='provider_jobs')
    op.drop_index(op.f('ix_provider_jobs_capability'), table_name='provider_jobs')
    op.drop_column('provider_jobs', 'idempotency_key')
    op.drop_column('provider_jobs', 'connection_id')
    op.drop_column('provider_jobs', 'capability')
    op.drop_column('provider_jobs', 'step_attempt_id')
    op.drop_column('provider_jobs', 'tenant_id')
    op.drop_index(op.f('ix_step_attempts_workflow_step_id'), table_name='step_attempts')
    op.drop_index(op.f('ix_step_attempts_workflow_id'), table_name='step_attempts')
    op.drop_index(op.f('ix_step_attempts_tenant_id'), table_name='step_attempts')
    op.drop_index(op.f('ix_step_attempts_status'), table_name='step_attempts')
    op.drop_table('step_attempts')
    op.drop_index(op.f('ix_quality_evaluations_tenant_id'), table_name='quality_evaluations')
    op.drop_index(op.f('ix_quality_evaluations_artifact_version_id'), table_name='quality_evaluations')
    op.drop_table('quality_evaluations')
    op.drop_index(op.f('ix_decision_requests_tenant_id'), table_name='decision_requests')
    op.drop_index(op.f('ix_decision_requests_status'), table_name='decision_requests')
    op.drop_index(op.f('ix_decision_requests_reason_code'), table_name='decision_requests')
    op.drop_index(op.f('ix_decision_requests_production_order_id'), table_name='decision_requests')
    op.drop_index(op.f('ix_decision_requests_plan_version_id'), table_name='decision_requests')
    op.drop_index(op.f('ix_decision_requests_agent_run_id'), table_name='decision_requests')
    op.drop_table('decision_requests')
    op.drop_index(op.f('ix_artifact_versions_tenant_id'), table_name='artifact_versions')
    op.drop_index(op.f('ix_artifact_versions_status'), table_name='artifact_versions')
    op.drop_index(op.f('ix_artifact_versions_plan_version_id'), table_name='artifact_versions')
    op.drop_index(op.f('ix_artifact_versions_artifact_id'), table_name='artifact_versions')
    op.drop_table('artifact_versions')
    op.drop_index(op.f('ix_plan_versions_tenant_id'), table_name='plan_versions')
    op.drop_index(op.f('ix_plan_versions_status'), table_name='plan_versions')
    op.drop_index(op.f('ix_plan_versions_agent_run_id'), table_name='plan_versions')
    op.drop_table('plan_versions')
    op.drop_index(op.f('ix_agent_events_tenant_id'), table_name='agent_events')
    op.drop_index(op.f('ix_agent_events_production_order_id'), table_name='agent_events')
    op.drop_index(op.f('ix_agent_events_event_type'), table_name='agent_events')
    op.drop_index(op.f('ix_agent_events_created_at'), table_name='agent_events')
    op.drop_index(op.f('ix_agent_events_agent_run_id'), table_name='agent_events')
    op.drop_table('agent_events')
    op.drop_index(op.f('ix_asset_refs_tenant_id'), table_name='asset_refs')
    op.drop_index(op.f('ix_asset_refs_production_order_id'), table_name='asset_refs')
    op.drop_index(op.f('ix_asset_refs_asset_id'), table_name='asset_refs')
    op.drop_table('asset_refs')
    op.drop_index(op.f('ix_artifacts_tenant_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_production_order_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_content_item_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_artifact_type'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index(op.f('ix_agent_runs_tenant_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_status'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_production_order_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_production_orders_tenant_id'), table_name='production_orders')
    op.drop_index(op.f('ix_production_orders_status'), table_name='production_orders')
    op.drop_index(op.f('ix_production_orders_project_id'), table_name='production_orders')
    op.drop_index(op.f('ix_production_orders_created_by_user_id'), table_name='production_orders')
    op.drop_index(op.f('ix_production_orders_content_item_id'), table_name='production_orders')
    op.drop_table('production_orders')
    op.drop_index(op.f('ix_consent_snapshots_tenant_id'), table_name='consent_snapshots')
    op.drop_index(op.f('ix_consent_snapshots_asset_id'), table_name='consent_snapshots')
    op.drop_table('consent_snapshots')
    op.drop_index(op.f('ix_content_items_tenant_id'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_status'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_project_id'), table_name='content_items')
    op.drop_table('content_items')
    op.drop_index(op.f('ix_assets_tenant_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_status'), table_name='assets')
    op.drop_index(op.f('ix_assets_project_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_created_by_user_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_projects_tenant_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_created_by_user_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_outbox_events_topic'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_tenant_id'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_published_at'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_available_at'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_aggregate_id'), table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_tenant_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_status'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_ip_profile_snapshots_tenant_id'), table_name='ip_profile_snapshots')
    op.drop_index(op.f('ix_ip_profile_snapshots_ip_profile_id'), table_name='ip_profile_snapshots')
    op.drop_table('ip_profile_snapshots')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_external_subject'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tenants_status'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    for enum_name in (
        'decisionstatus',
        'artifactversionstatus',
        'planversionstatus',
        'agentrunstatus',
        'productionorderstatus',
    ):
        op.execute(f'DROP TYPE IF EXISTS {enum_name}')
    # ### end Alembic commands ###
